### ISSUE TITLE
how to convert to json format for register/authenticate flow for makeCredential and getAssertion

### ISSUE THREAD

**Issue by xshadowlegendx** [flutter-institute/webauthn#8]
hello, so I am implementing a rust server with passkey support using `webauthn-rs` crate and want to do passkey with flutter ios and android and below is the format that I got from register init response from server

```json
{
    "publicKey": {
        "rp": {
            "name": "localhost",
            "id": "localhost"
        },
        "user": {
            "id": "iA1r9LG4TCu4dEKyb0MuUQ",
            "name": "+85512123777",
            "displayName": "+85512123777"
        },
        "challenge": "9mChGdkHX_u0_PvWaroZIqgosSFKgPGWLdnLN_G3i9c",
        "pubKeyCredParams": [
            {
                "type": "public-key",
                "alg": -7
            },
            {
                "type": "public-key",
                "alg": -257
            }
        ],
        "timeout": 60000,
        "attestation": "none",
        "excludeCredentials": [],
        "authenticatorSelection": {
            "requireResidentKey": false,
            "userVerification": "preferred"
        },
        "extensions": {
            "uvm": true,
            "credProps": true
        }
    }
}
```

after local verification success and needs to send attestation response back to the server to finalize register, the below json got from using `@github/webauthn-json` to convert between those format

```json
{
  "type": "public-key",
  "id": "fDcyyOOmrQDNnEgBuk9oHtTvC5cMMQre1b8p6vSMAbk",
  "rawId": "fDcyyOOmrQDNnEgBuk9oHtTvC5cMMQre1b8p6vSMAbk",
  "authenticatorAttachment": "platform",
  "response": {
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiOW1DaEdka0hYX3UwX1B2V2Fyb1pJcWdvc1NGS2dQR1dMZG5MTl9HM2k5YyIsIm9yaWdpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImNyb3NzT3JpZ2luIjpmYWxzZX0",
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVikSZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NFAAAAAK3OAAI1vMYKZIsLJfHwVQMAIHw3Msjjpq0AzZxIAbpPaB7U7wuXDDEK3tW_Ker0jAG5pQECAyYgASFYILQpWMVBkp8RPQsJaYUFPcuKH5XrjQPd1oXOzY7TEnFGIlggi4m9HoubTOHZ1nSolRlNaJgU_CJ-y0d1CWkJw1C2mjk",
    "transports": [
      "internal"
    ]
  },
  "clientExtensionResults": {
    "credProps": {
      "rk": true
    }
  }
}
```

this is from login init response from server

```json
{
    "publicKey": {
        "challenge": "7sG8WOtlPBrmng1sAhgX-kwaRofFZp6j_njQWykYeAI",
        "timeout": 60000,
        "rpId": "localhost",
        "allowCredentials": [
            {
                "type": "public-key",
                "id": "fDcyyOOmrQDNnEgBuk9oHtTvC5cMMQre1b8p6vSMAbk"
            }
        ],
        "userVerification": "preferred"
    }
}
```
after login success, and also using `@github/webauthn-json` to convert to below json format before sending to server

```json
{
  "type": "public-key",
  "id": "fDcyyOOmrQDNnEgBuk9oHtTvC5cMMQre1b8p6vSMAbk",
  "rawId": "fDcyyOOmrQDNnEgBuk9oHtTvC5cMMQre1b8p6vSMAbk",
  "authenticatorAttachment": "platform",
  "response": {
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiN3NHOFdPdGxQQnJtbmcxc0FoZ1gta3dhUm9mRlpwNmpfbmpRV3lrWWVBSSIsIm9yaWdpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImNyb3NzT3JpZ2luIjpmYWxzZX0",
    "authenticatorData": "SZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2MFAAAAAA",
    "signature": "MEUCIQD9-7lnUqbJOMYSeYZB03VbRvqvSr5GgQ8QqyY4EqxkIQIgL95Hlu7N6Pcmku9iQF4gyuztJJCcA1NX0O3vymbrxCI",
    "userHandle": "iA1r9LG4TCu4dEKyb0MuUQ"
  },
  "clientExtensionResults": {}
}
```

currently I am able to make the register response into format that `MakeCredentialOptions.fromJson` accept and proceed to make the credential and got back `NoneAttestation` object but do not know what to do next to be able to turn the attestation to format that the server accept next

```dart
final registerData = json.decode(registerInit.body)['publicKey'];

registerData['user']['id'] = base64.encode(utf8.encode(registerData['user']['id']));

registerData['clientDataHash'] = base64.encode(sha256.convert(utf8.encode(json.encode({
  'type': 'webauthn.create',
  'origin': 'https://7eba-45-115-82-8.ngrok.io',
  'crossOrigin': false,
  'challenge': registerData['challenge'],
}))).bytes);

registerData['credTypesAndPubKeyAlgs'] = (registerData['pubKeyCredParams'] as List).map((d) => [d['type'], d['alg']]).toList();

registerData['requireUserPresence'] = false;
registerData['requireResidentKey'] = registerData['authenticatorSelection']['requireResidentKey'];
registerData['requireUserVerification'] = registerData['authenticatorSelection']['userVerification'] == 'preferred';

final attes = await auth.makeCredential(MakeCredentialOptions.fromJson(registerData));

final d = await httpClient.patch(
  // Uri(scheme: 'http', host: 'localhost', port: 4222, path: '/users/webauthn/register'),
  Uri(host: '7eba-45-115-82-8.ngrok.io', path: '/users/webauthn/register', scheme: 'https'),
  headers: {'content-type': 'application/json', 'cookie': registerInit.headers['set-cookie']!}, body: attes???);

print(d.statusCode);
```

**Comment by killermonk** [comment]
Alright, first things first. I dug into the webauthn-rs libraries to see what it is expecting. I don't think my library is going to work with it in its current state because this library is using self attestation. The webauthn-rs library supports all the other attestation types _except_ for the "None" type.

I'll have to dig in to the other types and see which ones might make the most sense for this library, if any. I might be able to get the packed format working, but I'd have to dig in at a later date.

Also, my library right now does not support JSON serialization of the Attestations, which feels like I missed some functionality. It does support serializing them into CBOR format, but that's not what you're looking for. (Though you could use https://docs.rs/cbor/latest/cbor/ to Decode the CBOR server-side.)

For this attestation object, the JSON for this would be created something like follows:
```
{
  "authData": base64.encode(attes.authData),
  "fmt": "none",
  "attStmt": {}
}
```

Again, though, it looks like the webauthn-rs library doesn't support this format, so this might now be very helpful.

**Comment by xshadowlegendx** [comment]
hello @killermonk thanks for the reply, if this library works with the `webauthn-rs` in the near future then I will help you test it then 😄 😄 😄

**Comment by killermonk** [comment]
Hey @xshadowlegendx, I did a thing today.

If you want to update your pubspec.yaml to the following for the webauthn extension, you should be able to test out the new packed attestation with your library

```
  webauthn:
    git:
      url: https://github.com/flutter-institute/webauthn.git
      ref: feature/packed-attestations
```

I haven't merged or released this change, yet, because I've only done very minimal validation that the format looks correct. If you want to test it out, that would be awesome.

I also added the `.toJson()` handling to the Attestation object. So you should be able to just call your code as is (it returns a packed attestation by default instead of none), then use `attes.toJson()` to get the payload to send to your server.

Let me know what you think!

**Comment by xshadowlegendx** [comment]
hello @killermonk, so I tested the updates you made and the response does not seems to be same as what `webauthn-rs` server expected yet and the json string is in base64 of a cbor format? what are the additional steps for me to do in order to convert it to format such as the below which the server accepts for finalizing the registration?

```json
{
  "type": "public-key",
  "id": "fDcyyOOmrQDNnEgBuk9oHtTvC5cMMQre1b8p6vSMAbk",
  "rawId": "fDcyyOOmrQDNnEgBuk9oHtTvC5cMMQre1b8p6vSMAbk",
  "authenticatorAttachment": "platform",
  "response": {
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiOW1DaEdka0hYX3UwX1B2V2Fyb1pJcWdvc1NGS2dQR1dMZG5MTl9HM2k5YyIsIm9yaWdpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImNyb3NzT3JpZ2luIjpmYWxzZX0",
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVikSZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NFAAAAAK3OAAI1vMYKZIsLJfHwVQMAIHw3Msjjpq0AzZxIAbpPaB7U7wuXDDEK3tW_Ker0jAG5pQECAyYgASFYILQpWMVBkp8RPQsJaYUFPcuKH5XrjQPd1oXOzY7TEnFGIlggi4m9HoubTOHZ1nSolRlNaJgU_CJ-y0d1CWkJw1C2mjk",
    "transports": [
      "internal"
    ]
  },
  "clientExtensionResults": {
    "credProps": {
      "rk": true
    }
  }
}
```

**Comment by killermonk** [comment]
My bad. I got tunnel vision and didn't actually check back on your data.

Everything I'm returning from the attestation would be what goes in the `attestationObject` portion of your payload. In a test implementation I did for chrome, it looks like the `attestationObject` needs to be the base64 of the cbor object. So you would want something like `'attestationObject': base64.encode(attes.toCBOR()),`

The `.toJson()` returns a string that is JSON representation of the attestationObject with the byte data in base64 format. Looking at your expected payload and my chrome test, that doesn't seem like what you need, see the CBOR stuff above.

The `clientDataJSON` is going to be the the `utf8.encode`d payload that you used to create the clientDataHash that is passed as the argument to the library. So something like this, then you can reuse that data.
```
final clientDataJSON = utf8.encode(json.encode({
  'type': 'webauthn.create',
  'origin': 'https://7eba-45-115-82-8.ngrok.io',
  'crossOrigin': false,
  'challenge': registerData['challenge'],
}));
registerData['clientDataHash'] = base64.encode(sha256.convert(clientDataJSON).bytes);
```

The rest of that data is things that your app, as the authenticator, should managed properly as part of the exchange.

**Comment by killermonk** [comment]
While I was testing this all more thoroughly, I realized that I was not using url-safe base64, so the library is now updated to use that properly everywhere.

I'll add helper functions to the Authenticator for this at a future date, but here's the relevant code to transform the responses from the Authenticator to the Relying Party:

Make Credential Attestation
```dart
final credentialId =
    credential.attestation.getCredentialIdBase64();
final attestationResponse = json.encode({
  'type': 'public-key',
  'id': credentialId,
  'rawId': credentialId,
  'response': {
    'clientDataJSON': base64Url.encode(clientDataJSON),
    'attestationObject':
        base64Url.encode(credential.attestation.asCBOR()),
  },
});
```

Get Assertion Response
```dart
final credentialId = base64Url.encode(assertion.selectedCredentialId);
final assertionResponse = json.encode({
  'type': 'public-key',
  'id': credentialId,
  'rawId': credentialId,
  'response': {
    'authenticatorData': base64Url.encode(assertion.authenticatorData),
    'clientDataJSON': base64Url.encode(clientDataJSON),
    'signature': base64Url.encode(assertion.signature),
    'userHandle': base64Url.encode(assertion.selectedCredentialUserHandle),
  },
});
```

Now that I've tested these more thoroughly, I'll merge them within a few days and push a new version to pub.

Then I'll work on extensions.

**Comment by xshadowlegendx** [comment]
hello @killermonk  sorry for the late reply, currently the register finalize endpoint accepted the `attestationResponse`, but had trouble finalizing it at the backend, it returns `Err(OpenSSLError(ErrorStack([])))` without any more detail

**Comment by killermonk** [comment]
If I had to guess, I think this is probably related to my stuff not currently handling extensions. I've built a little test script using a node library to verify everything with 3rd party code locally and it works with that one as long as I don't have extensions that need processing.

**Comment by xshadowlegendx** [comment]
ohh it might because of it, currently the `webauthn-rs` does not have option to not set the extensions or at least the doc does not seem to have mention about it that I am aware of

**Comment by killermonk** [comment]
I'm planning on working on extensions this week, so we'll see how it goes

**Comment by davidcaseria** [comment]
I am also working on implementing a `webauthn-rs` server. To confirm, is it expected that this library is incompatible with `webauthn-rs`, or do some of the suggestions above work to support passkey registration/authentication? The branch mentioned above appears to not exist anymore. Let me know if any help is needed. I'm happy to test the integration between these two libraries.

I am currently running into the same `Err(OpenSSLError(ErrorStack([])))` issue without additional detail so am a bit stuck at the moment.

**Comment by killermonk** [comment]
@davidcaseria the above mentioned branch was merged into `master` and a new version deployed. So all those changes are now in the latest version of the package on pub.dev.

At what point in the process are you getting that error? Is it being throw on the flutter side of things or on the `webauthn-rs` package after the result is returned?

I haven't had time to work on the extensions support yet. From some reading I was doing on the webathn-rs package (I can't remember where) they were saying that extensions were required for a request to succeed. So it might not be compatible at the moment. Ironically, requiring extensions appears to violate the webauthn standards per https://www.w3.org/TR/webauthn/#sctn-extensions

> All [WebAuthn Extensions](https://www.w3.org/TR/webauthn/#webauthn-extensions) are OPTIONAL for both clients and authenticators. Thus, any extensions requested by a [Relying Party](https://www.w3.org/TR/webauthn/#relying-party) MAY be ignored by the client browser or OS and not passed to the authenticator at all, or they MAY be ignored by the authenticator. Ignoring an extension is never considered a failure in WebAuthn API processing, so when [Relying Parties](https://www.w3.org/TR/webauthn/#relying-party) include extensions with any API calls, they MUST be prepared to handle cases where some or all of those extensions are ignored.

But it is what it is. If you can give me some more details about what part of the stack is generating that error, I might be able to dig in a little more.

**Comment by davidcaseria** [comment]
@killermonk ah, that makes sense the branch was merged. Below is an excerpt from my Flutter code on how I'm using this library:
```
final api = WebAPI();
final auth = Authenticator(true, true);
final createOpts = // get CreateCredentialOptions from backend
final makeOpts = await api.createMakeCredentialOptions(origin, createOpts, true);
final attestation = await auth.makeCredential(makeOpts.$2);
final res = await api.createAttestationResponse(makeOpts.$1, attestation);
// finish registration with AttestationResponse -- ERROR
```

When I pass the `AttestationResponse` object to the [`finish_passkey_registration`](https://docs.rs/webauthn-rs/0.4.8/webauthn_rs/struct.Webauthn.html#method.finish_passkey_registration) function in the `webauthn-rs` library, I believe I hit an error [here](https://github.com/kanidm/webauthn-rs/blob/908b2d9cf8a8fb8e1f600ee67d5b0dd0f47b3f20/webauthn-rs-core/src/attestation.rs#L428). My debugger isn't cooperating so I haven't been able to verify with 100% confidence, but from my logging debug statements I'm fairly confident this is where the error occurs.

It's certainly possible it is an issue with extensions, however from analyzing the code in the library and where I think the error occurs, it doesn't appear obvious to me that is the case, but I could certainly be wrong.

Thank you for the help!

**Comment by killermonk** [comment]
That's super odd, because it shouldn't ever be getting to that with the Attestation being generated.

It should hit this code for the self attestation: https://github.com/kanidm/webauthn-rs/blob/908b2d9cf8a8fb8e1f600ee67d5b0dd0f47b3f20/webauthn-rs-core/src/attestation.rs#L488

The `attStmt` payload only includes the 'alg' and 'sig' keys, so I'm not sure why the code would think that 'x5c' was present.

I added some static helper methods that might maybe help. You can remove your `final auth =` line and replace the call to the auth with this:
```
final attestation = await Authenticator.handleMakeCredential(makeOpts.$2);
```

That will ensure that the correct values for authentication/strongboxRequired are passed to the authenticator based on the creationOptions. I doubt this is the problem, though.

The attestation being returned should look like the following encoded as CBOR:
```
{
  'authData': base64Url.encode(authData),
  'fmt': 'packed',
  'attStmt': {
    'alg': -7,
    'sig': base64Url.encode(signature),
  },
}
```

**Comment by davidcaseria** [comment]
Thanks @killermonk. This is the strangest thing, now my code occasionally works and other times fails.

You are right though about the code path. It looks like the code is actually failing [here](https://github.com/kanidm/webauthn-rs/blob/908b2d9cf8a8fb8e1f600ee67d5b0dd0f47b3f20/webauthn-rs-core/src/crypto.rs#L61) after further debugging. This appears to indicate sometimes the signatures are valid and other times are invalid?

**Comment by xshadowlegendx** [comment]
hello @killermonk thanks for your awesome work, I was implementing oauth for my passkey server and use oidc client to connect to my passkey server instead but I also want to make it work natively instead of using oauth, will try to use the latest branch and test out the `Err(OpenSSLError(ErrorStack([])))` again

**Comment by killermonk** [comment]
@davidcaseria I'll have to look into that. I have had my unit tests fail a couple time on signature verification, but they have always passed the next time I ran them so I didn't dig in deeper. I'll see what I can figure out.

**Comment by killermonk** [comment]
Alright, so I have verified that some keys being generated are invalid. I haven't found a root cause, yet, though. I was able to get 3 failed keys in about 400 tests. The following public key is one that was generated and is, apparently, invalid.
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbMQppG6vSpjYwVAijPl4EI4jFG4d
TGu8dLmQv4khX4IAVHq+mUY1vaWzbX6TIlIddbj8zgbp5MxSzf5ThL419Q==
-----END PUBLIC KEY-----
```
Its raw data is
```
{
  kty: 'EC',
  crv: 'P-256',
  x: 'bMQppG6vSpjYwVAijPl4EI4jFG4dTGu8dLmQv4khX4I=',
  y: 'AFR6vplGNb2ls21+kyJSHXW4/M4G6eTMUs3+U4S+NfU='
}
```
When I use the following command `openssl ec -pubin -in pubkey.pem -noout` the command fails and it is unable to read the key.

I'm digging in and trying to figure out why there are any invalid keys being generated.

**Comment by davidcaseria** [comment]
FWIW, the ratio of invalid signatures seems to be much higher for me. I just had a scenario where 4 signatures failed in a row before the 5th one succeeded. If there are any logs or anything else I can provide to be helpful, please let me know.

**Comment by killermonk** [comment]
Root cause found. There is a bug in the code converting BigInts to bytes that improperly converts any number that is divisible by 256 🤦 

https://github.com/flutter-institute/byte_extensions/issues/1

**Comment by killermonk** [comment]
I've just published a new version of the webauthn package (0.2.0) that I hope should resolve this.

This includes the new version of byte_extensions (0.0.3) that fixes the issue with keys being serialized incorrectly.

Thanks for all the back and forth and extra data on this. Let me know if this cleans things up.

**Comment by davidcaseria** [comment]
I'm still seeing intermittent invalid signatures after upgrading to 0.2.0. Is there any helpful information I can provide?

**Comment by killermonk** [comment]
@davidcaseria let's open a new ticket to discuss, since this one is getting a bit long and we're moving into a new topic. In that ticket, if you can provide me with one or more of the attestation response payloads I can dig in and make sure all the data there is valid, which will give me a starting point. Also, is this the same error as before or a new error in a different place?
